### ISSUE TITLE
Gamepad not working

### ISSUE THREAD

**Issue by Skiski** [snapcrafters/spelunky#3]
Hi,

I cannot play the game with my wired xbox 360 gamepad. It works great with the snap version of trackmania nation.

Only the "A" button works and the start button seems to skip the video at the start of the game.

When I try to rebind the keys in the game, none of the gamepad buttons are recognized, not even the "A" button.

I don't know if it is linked to the error about the two missing files in assets.

**Comment by popey** [comment]
Confirmed, but unfortunately this appears to be an upstream issue. I grabbed the Windows build of Spelunky Classic HD and it malfunctions in *exactly* the same way. So while it's a problem, it's an upstream one, so should be filed at https://github.com/yancharkin/SpelunkyClassicHD

**Comment by popey** [comment]
Actually, don't pester upstream:-

"Update. For those who keep asking about gamepad support.
As far as I know only Xbox 360 gamepads are working and I'm not sure that's true for all platforms. Other gamepads may or may not work, I don't know, try it yourself. And please stop asking about it!"

**Comment by Skiski** [comment]
Thanks for the answer.
For those asking, you can use antimicro which works great to map joypad inputs to keyboard keys.
